### ISSUE TITLE
Conflicts when parsing tables

### ISSUE THREAD

**Issue by frank-lenormand** [six-two/mkdocs-badges#4]
Hi,

I use badges and tables in my documentation:

```md
|badge_name|value|class_name|
```

```md
| 🔗 | information (count) | grouping |
| - | ------------------- | :------: |
| [🔗](#foo) | server |
```

When the site builds, the above results in the following warnings:

```
WARNING -  [badges] [a.md:1] Parsing error: Unknown attribute: ' grouping '
WARNING -  [badges] [a:2] Parsing error: Unknown attribute: ' :------: '
```

Is there any way to make parsing more robust, and avoid producing those false negatives?

Note that the same warnings show up when the table has more than 3 columns, which is an easier case to handle in my opinion.

Further: handling badges in tables.

Thanks!

**Comment by six-two** [comment]
Hi,

thanks for the bug report! I will look into the issue.

I know that tables were tricky, which is why I added a test table to one of the test pages ([source](https://raw.githubusercontent.com/six-two/mkdocs-badges/main/docs/test/basic.md)/[rendered](https://mkdocs-badges.six-two.dev/test/invalid/)). My guess is, that my table detection logic does not recognize your table header row:
```
| - | ------------------- | :------: |
```

Sadly I can not rely on a set maximum length, since you can define badges like this one:
```
|with properties 1|test|c:text to copy|l:https://example.com|.html-class|class:html-class2|
```

Personally I always use at least three dashes and have not yet needed to the alignment settings (like `:---:`). I will try to make the parsing more robust and add an option to disable warnings from the plugin.

**Comment by six-two** [comment]
The problem was the single dash. I was under the assumption, that three or more dashes were needed for every field in the row between table header and body. The regex has been adjusted, and your problematic table now works for me ([see latest tests](https://mkdocs-badges.six-two.dev/test/invalid/)). Can you please update the plugin to version 0.4.2 and tell me if you have any more broken tables?

By the way: By adding `disable_warnings: True` to the plugin config in your `mkdocs.yml`, you can also disable warnings. But I would not recommend it, since it can hide real issues. In your case the warnings were actually useful, since the third line (with the link and `server` text) was actually parsed as a badge before this fix.

**Comment by frank-lenormand** [comment]
Seems to work, thanks for the quick fix!
