### ISSUE TITLE
Compatibiity with markdown extensions for emoji and icons

### ISSUE THREAD

**Issue by byrnereese** [six-two/mkdocs-badges#5]
I love mkdocs-badges. I have started to use it for our documentation at ringcentral.com. I also have been using material-mkdocs, which comes with a nice feature where I can use a simple markdown syntax to embed an icon. 

https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/

I want to use this in my badges, so that I can have something like this:

```
| :fontawesome-regular-face-laugh-wink: | byrnereese |
```

However, mkdocs-badges prevents the emoji text from being parsed and it is output literally. 

One possible fix is to include an option of somekind that will add "markdown" to the outputted HTML so that the md_in_html plugin can do its thing. For example:

```
<span class="badge-group" markdown>
    <span class="badge badge-normal"><span class="sep"> [</span><span class="title">:fontawesome-regular-face-laugh-wink:</span><span class="sep"> | </span><span class="value">1.x</span><span class="sep">] </span></span>
</span>
```

Alternatively, you could implement this as a markdown extension, which arguably is the better option - as I think the utility of this plugin is great, and that would give this solution a much large audience.

**Comment by six-two** [comment]
Hi, and thanks for the feedback! I also love the Material for MkDocs theme, so I agree that mkdocs-badges should support features like emojis if possible.

I just added a [test case](https://mkdocs-badges.six-two.dev/test/theme/) for your use case and it already seems to work for me with no extra configuration: 

![mkdocs-badges-emoji-issue](https://github.com/six-two/mkdocs-badges/assets/20253663/ec80a7cc-4a6a-4c7a-be1c-c62b83a3305d)

Can you please confirm:
1. that you are using the latest version of `mkdocs-material` and `mkdocs-badges`
2. that emojis render correctly outside of badges
3. that the problem is still there if you disable (all) other plugins

Otherwise can you please give me a minimum viable example (or the link to your full project), so that I can reproduce the issue?

**Comment by byrnereese** [comment]
I have confirmed this works. I am too embarrassed to admit the root cause as it was a bone-headed user error. Apparently, you need to enable the emoji markdown extension. If you only knew how many hours I spent trying to get this to work!

Thank you for replying quickly and showing me it was possible. Without that, I wouldn't have found my error.
